// <auto-generated />
namespace ViewModels.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddMoviesMoreInfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMoviesMoreInfo));
        
        string IMigrationMetadata.Id
        {
            get { return "202003221441081_AddMoviesMoreInfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
